#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: letmein
POSTGRES_SQL_HOST: 192.168.1.216
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: spcloud

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <YOUR EMAIL ADDRESS>
EMAIL_PASSWORD: <YOUR PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}